let transcriptedText = [
    { 0: "Are you one of those who has plenty of business ideas, but you fail to execute upon them because you don't know where to even start? Are you one of those who are always brimming with ideas? And you are like, Oh my God, I thought of this five years back" },
    { 16: "but you know what? Somebody else did something about it." },
    { 20: "The problem is never ideas. The problem is not that you dont know what to do. The problem is that there is no guide, there is no theory, there is no structure to how do you even begin to execute your idea. The truth is, nothing is organised for you to create a step by step guide. My name is Uncle Varaku. I'm the cofounder of nearby.com. I've been an entrepreneur for the last 12 years, raised more than $40 million in funding, got nearby to a sales of over $100 million annually" },
    { 49: "And then I quit in 2019, stepped down as the CEO to help build more entrepreneurs. And I've condensed the 12 years of my experience into 16 hours, a course that I call The Complete Guide to Starting Up 8 chapters that will take you through every possible step that you need to know to start your own business. How do you pick a startup idea? How do you validate the strength of that?" },
    { 81: "How do you decide on the cofounding team? How do you decide the split of equity between your cofounder and yourself, whether you should go for funding or not? How do you decide the first version of your product? How do you build that out? How do you price that product? How do you launch it, market it, and get your first thousand customers or so? Everything that you need to know, packaged in a form that's consumable, coming from somebody who's done it. I've made so many mistakes in the last 12 years." },
    { 111: "I would love for all of you to learn from those mistakes and never find yourself anymore in a situation where you say I have so many ideas, but I don't know where to even begin." },
    { 123: "You can begin your idea journey right now. Sign up for this course and I will see you inside of it." }
]
